<div id="networkHelp">
    <div class="mainHeadingHelp text-center">
      Network Analysis Module
    </div>
 
    <div class="helpText">
      <p class="text-muted"> The Network Analysis module of Social Media Analysis Tool VISHLESHAKEE provides
        the functionality of analyzing different types of networks obtained from the system as well as
        networks that are being imported from the external source. As, the social media data is highly
        relational analysing them from the relational perspective can help gaining a better insight.
        The networks currently being supported by the system can be seen from the Network choice
        selector in the query panel. The module can generate a network given by the user with the required mandatory information and can perform various analysis on them.
        The rest of the manual provide the steps to be followed for generating a network and doing
        suitable analysis on them.
      </p>
    </div>
    
    <p> <b>Minimum User Device Specification:</b> 4 GB (RAM) </p>
    <p> <b>Recommended User Device Specification:</b> >= 8 GB (RAM) </p>
 
    <div id="trendingEventsHelp">
      <p class=" helpHeadings m-0"> Network Generation <p>
 
          <p class="helpsubHeadings m-0"> Network Generation from User Inputs<p>
              For generating the network, a user is required to provide the following mandatory information.
 
              <div>
                <figure class="figure">
                    <img class="center" src="public/Screens/net1.PNG" id="netpics"/>
                    <figcaption class="figure-caption text-center "> Network Generation Panel </figcaption>
                </figure>
              </div>
 
 
              <ol>
                <li> Query: The query is the input given by the user it may be a hashtag or a mention or a
                  user ID, or a keyword. Sample Inputs: #JNU, @ndtv, narendra modi, cricket</li>
                <li>From Date: Starting date of the range query</li>
                <li>To Date: Ending date of the range query</li>
                <li> Network Size: The upper bound on the number of nodes to be generated for the
                  query. Say, 50 or 100.</li>
                <li>Network Choice: The selector provides the facility to generate different networks. One
                  need to select appropriate network to be generated for the given query</li>
              </ol>
 
              It is to be noted that the choice of the network should be compatible with the given query.
              i.e. if the given input query is a hashtag then the following networks should be only chosen
              for the network generation.
 
              <ol>
                <li>Hashtag-Hashtags.</li>
                <li>Hashtag-Mentions.</li>
                <li>Hashtag-User</li>
              </ol>
 
              Similarly, if the given input is a mention then the following networks are valid:
 
              <ol>
                <li>Mention-Mentions</li>
                <li>Mention-Hashtags.</li>
                <li>Mention-Users.</li>
              </ol>
    </div>
    
        Once, all the inputs are being provided the user is required to click on the Generate Network button
        placed by the side of the input box in the query panel. This will result in the graph to be
        generated. A card will show up down the query panel with the basic information about the
        network being generated. The loader inside the card appears marking the process running for
        generating the graph.
        Wait, till the loader disappears from the card.
    <p class="helpsubHeadings m-0"> Network Generation from External File Upload<p>
        A network can also be generated by importing data from external source. The module currently
        accepts .csv files as edgelist (in the format of [src,dst,count]) as an external source for network
        generation.
 
 
        <div>
          <figure class="figure">
            <img class="center" src="public/Screens/net2.PNG" id="netpics"/>
            <figcaption class="figure-caption text-center "> Network View Panel </figcaption>
          </figure>
        </div>
 
        Once, the loader disappears,
        The user is required to click on the view-graph text present on the card. Clicking on the
        text will show up the generated graph to the user in the Graph View Panel.
        Let the graph appear completely in the panel with all the edges and nodes rendered and
        wait till the graph becomes stable. It will take few seconds for the graph to be stable depending
        upon your system specifications.
        Note: It is to be noted that performing some analytical operations on the unstable graph may
        result in failing operations.)
        <br>
        <br>
        Once, the graph is being generated a number of operations can be performed upon that. The
        analytical operations supported by our module with the steps to be followed are given below: -
        <br>
        <br>
        For, going for performing the analytical operations on the graph the user needs to click on
        the PERFORM ANALYSIS button present in the right-hand side of the screen.
        Clicking, on the button will provide the user the choice buttons for the analytical operations:
 
        <p class="helpHeadings m-0"> Centrality <p>
            In social networks, centrality is an indicator of identifying important nodes in a network. Our
            module provides the following variants of centrality:
            <br>
 
            <div>
              <figure class="figure">
                <img class="center" src="public/Screens/net3.PNG" id="netpics"/>
                <figcaption class="figure-caption text-center "> Network Centrality </figcaption>
              </figure>
            </div>
 
            <ol>
              <li>Degree Centrality</li>
              <li>Eigen Value Centrality</li>
              <li>Betweeness Centrality</li>
              <li>Page Rank Centrality</li>
            </ol>
 
            <br>
            For performing the centrality operation on the network. The following steps need to be
            followed:
 
            <ol>
              <li>Click on the blue colored Centrality Tab</li>
              <li>Select the algorithm choice for the centrality finding provided via the radio buttons.</li>
              <li>Click on the EXEC button.</li>
            </ol>
 
            <br>
            Upon success of the query the resultant graph will be displayed in the same panel. Zoom
            out the division for letting the graph to be displayed as a whole.
 
            <p class="helpHeadings m-0"> Community Detection <p>
                In social networks Community Detection aims to group similar nodes together, thus discovering hidden communities present. Our module provides the following variants of Community
                Detection
                <br>
 
                <div>
                  <figure class="figure">
                    <img class="center" src="public/Screens/net4.PNG" id="netpics"/>
                    <figcaption class="figure-caption text-center "> Community Detection </figcaption>
                  </figure>
                </div>
 
                <ol>
                  <li>Async Fluidic</li>
                  <li>Label Propagation</li>
                  <li> Grivan Newman </li>
                </ol>
                <br>
                Steps to be followed for finding out the communities in the graph
                <ol>
                  <li>Click on the community Detection Tab</li>
                  <li>Select the appropriate algorithm choice, if you select Async Fluidic as the algorithm you
                    need to provide the number of communities to be generated</li>
                 <li>Click on the EXEC button.</li>
                </ol>
                <br>
                In the above Community Detection sample output each color defines a community where the
                nodes with similar color belongs to the same community.
                Upon successful query a graph will be displayed in the same panel with communities in
                different colors.
 
                <p class="helpHeadings m-0"> Shortest Paths <p>
                    Shortest path aims to find a shortest path between a pair of nodes in the network. Our module
                    provides the following variants of Shortest Path.
 
                    <ol>
                      <li>Shortest Path</li>
                      <li>K-Shortest Path</li>
                      <li>All Possible Shortest Path per depth</li>
                    </ol>
                    <br>
                    Steps for finding the shortest path in the graph is as follows:
 
                    <ol>
                      <li> Click on the Shortest Path Tab</li>
                      <li> Provide Source and Destination node. One can provide this information directly in the
                        query box or by clicking on the nodes in the graph. The selection of two nodes from the graph:
                        First node can be selected by a direct single click while the selection of the next node
                        requires Cmd+click on the node.</li>
                      <li>Select the Algorithm choice and Click on the EXEC button</li>
                    </ol>
                    <br>
                    On successful query the source and target node will be enlarged also the edge between them
                    will be bold. If any intermediate node exists between the two nodes, then the intermediate
                    node will also be enlarged colored in different color from the source and destination node.
 
                    <p class="helpHeadings m-0"> Link Prediction <p>
                        Link prediction aims to predict future connections between nodes based upon their present
                        neighbbourhood. Our module provides the following variants of link prediction.
 
                        <div>
                          <figure class="figure">
                            <img class="center" src="public/Screens/net5.PNG" id="netpics"/>
                            <figcaption class="figure-caption text-center "> Link Prediction </figcaption>
                          </figure>
                        </div>
 
                        <ol>
                          <li>Adamic Adar</li>
                          <li>Jaccard Coefficient</li>
                        </ol>
 
                        The steps to be followed for the link prediction is as follows:
 
                        <ol>
                          <li>Click on the link prediction Tab</li>
                          <li>Select the Algorithm choice.</li>
                          <li>Select a node from the graph.</li>
                          <li>Provide the number of top k links to be predicted.</li>
                          <li>Click on the EXEC button</li>
                        </ol>
                        Upon successful query the query node and the predicted nodes will be highlighted in
                        different color and the predicted edges will be appearing in dark black color.
 
                        <p class="helpHeadings m-0">Union of Networks<p>
                            Union aims to combine different networks into a single network. Prerequisite: Generate two
                            graphs from the Network Generation Panel. Make sure both the graphs are selected.
 
 
                            <div>
                              <figure class="figure">
                                <img class="center" src="public/Screens/union.PNG" id="netpics"/>
                                <figcaption class="figure-caption text-center "> Network Union </figcaption>
                              </figure>
                            </div>
 
 
                            <ol>
                              <li>Select two graphs</li>
                              <li>Click on Union View Panel.</li>
                              <li>Click on EXEC Button</li>
                            </ol>
 
                            Upon successful query a graph with the union of two graphs will be displayed. Here in the
                            Figure: Union Network node with similar color belongs to one of the input networks and nodes
                            with the red color describes the nodes that are common to all the input networks.
 
                            <p class="helpHeadings m-0">Intersection of Networks<p>
                                Intersection aims to find out the common nodes in a given number of input networks.
                                Perquisite is as same as the union operations. Steps:
 
                                <div>
                                  <figure class="figure">
                                    <img class="center" src="public/Screens/intersection.PNG" id="netpics"/>
                                    <figcaption class="figure-caption text-center "> Network Intersection</figcaption>
                                  </figure>
                                </div>
 
                                <ol>
                                  <li>Select two graphs</li>
                                  <li>Click on Intersection View Panel.</li>
                                  <li>Click on EXEC Button</li>
                                </ol>
 
                                Upon successful query a graph with the intersection of two graphs will be displayed. Here in
                                the Figure:Intersection Network nodes with red color determines the common nodes where as
                                nodes with violet color denotes the nodes that are connected with the intersecting nodes and
                                the nodes in dim denotes that are not satisfying the earlier criteria.
 
                                <p class="helpHeadings m-0">Difference of Networks<p>
                                    Difference of networks aims to discover uncommon nodes from a network with an another
                                    network. Upon successful query a graph with the intersection of two graphs will be displayed.
                                    Perquisite is as same as the union operations. Steps:
 
                                    <div>
                                      <figure class="figure">
                                        <img class="center" src="public/Screens/difference.PNG" id="netpics"/>
                                        <figcaption class="figure-caption text-center "> Network Difference </figcaption>
                                      </figure>
                                    </div>
 
                                    <ol>
                                      <li>Select two graphs</li>
                                      <li>Click on Difference View Panel.</li>
                                      <li>Input the network IDs as per the ordering in which you want to perform the difference.Say, if you want to perform difference of network 1 from network 2, then you
                                        should add network 2 first and then network 2</li>
                                      <li>Click on Perform Difference Button.</li>
                                    </ol>
 
                                    <p class="helpHeadings m-0">Deletion of a node from the Network<p>
                                    A node can be deleted from the network by double clicking on the node. It will result in the deletion of the node alongwith its related edges. The deletion can be 
                                    made by double clicking on the node.
 
                                        <div>
                                          <figure class="figure">
                                            <img class="center" src="public/Screens/deletion.PNG" id="netpics"/>
                                            <figcaption class="figure-caption text-center "> Node Deletion </figcaption>
                                          </figure>
                                        </div>

                                        <p class="helpHeadings m-0">Distributed Processing of Large Scale Networks with Apache Spark<p>
                                    VISHLESHAKEE faciliates processing of large scale network with Apache Spark distributed computing framework.

                                    <div>
                                        <figure class="figure">
                                          <img class="center" src="public/Screens/sparkNA.PNG" id="netpics"/>
                                          <figcaption class="figure-caption text-center "> Apache Spark for Distributed Network Processing</figcaption>
                                        </figure>
                                      </div>

  </div>